CREATE TABLE USER
(
  ID           INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  ACCOUNT      VARCHAR(100),
  NAME         VARCHAR(50),
  TOKEN        VARCHAR(36),
  GMT_CREATE   BIGINT,
  GMT_MODIFIED BIGINT
);